### ISSUE TITLE
No Tracking on Build

### ISSUE THREAD

**Issue by Z0R4NG3** [sergiobd/ViveTrackerUtilities#4]
Hello,

I recently found this package and it has been very helpful. Your Read Me was very informative and easy to follow. However when I build the project there is no tracking even though it all works perfectly in Editor. I've included the dll in the build folder plugins and corrected the file path in CopyOpenVr.cs.
Is there anything I'm missing? I'm using Unity 2018.2.6 if that matters.

Thanks,
-Zack M.

**Comment by sergiobd** [comment]
Hi,
I'm glad the package has been helpful. I can only think of a problem in the path name. I suggest you check the log files to debug the error. I should be here:
![image](https://user-images.githubusercontent.com/4733666/73619552-31dc6e80-4671-11ea-8e65-da957ccee456.png)

Image from [Log Files manual page](https://docs.unity3d.com/Manual/LogFiles.html).

**Comment by Z0R4NG3** [comment]
Thanks for the timely response.  I will check the log file and double check
that the path is correct.

**Comment by sergiobd** [comment]
@Z0R4NG3, could you solve the issue?

**Comment by Z0R4NG3** [comment]
Yes I did solve the problem. My path was correct but on my machine there
were two files by that name in slightly different places. I changed the
path to point to the other and now the program works fine.

**Comment by sergiobd** [comment]
Glad to read that. Closing this issue now.
